baseURL = "https://example.org/"
languageCode = "en-us"
title = "Manhattan Bridges Marathons"
theme = "hugo-scroll"
enableEmoji = true

# This is a "one page"-website.
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

# Reference-only: see themes/hugo-scroll/exampleSite/hugo.toml for full options.
[params]
  title = "Manhattan Bridges Marathons"
  description = "This is a shitpost. Or is it???"

[caches]
  [caches.images]
    dir = ':cacheDir/images'